apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tekton-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJhcmFtb3MyMCIsInBhc3N3b3JkIjoiZGNrcl9wYXRfQlBRWjh1RERoSVpjMzdkRWZYdjk0aklwc0hJIiwiZW1haWwiOiJhZHJpYW5qb3NlcjIwQGdtYWlsLmNvbSIsImF1dGgiOiJZWEpoYlc5ek1qQTZaR05yY2w5d1lYUmZRbEJSV2poMVJFUm9TVnBqTXpka1JXWllkamswYWtsd2MwaEoifX19
kind: Secret
metadata:
  name: regcred
  namespace: default
type: kubernetes.io/dockerconfigjson
