apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tekton-pvc
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJhcmFtb3MyMCIsInBhc3N3b3JkIjoiZGNrcl9wYXRfQlBRWjh1RERoSVpjMzdkRWZYdjk0aklwc0hJIiwiZW1haWwiOiJhZHJpYW5qb3NlcjIwQGdtYWlsLmNvbSIsImF1dGgiOiJZWEpoYlc5ek1qQTZaR05yY2w5d1lYUmZRbEJSV2poMVJFUm9TVnBqTXpka1JXWllkamswYWtsd2MwaEoifX19
kind: Secret
metadata:
  name: regcred
  namespace: default
type: kubernetes.io/dockerconfigjson
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pipeline-run-access
  namespace: default
subjects:
  - kind: ServiceAccount
    name: tekton-service-account
    namespace: default
roleRef:
  kind: Role
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-service-account-admin-binding
subjects:
  - kind: ServiceAccount
    name: tekton-service-account
    namespace: default
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
