apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tekton-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOnsidXNlcm5hbWUiOiJhcmFtb3MyMCIsInBhc3N3b3JkIjoiZGNrcl9wYXRfQlBRWjh1RERoSVpjMzdkRWZYdjk0aklwc0hJIiwiZW1haWwiOiJhZHJpYW5qb3NlcjIwQGdtYWlsLmNvbSIsImF1dGgiOiJZWEpoYlc5ek1qQTZaR05yY2w5d1lYUmZRbEJSV2poMVJFUm9TVnBqTXpka1JXWllkamswYWtsd2MwaEoifX19
kind: Secret
metadata:
  name: regcred
  namespace: default
type: kubernetes.io/dockerconfigjson
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: admin-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: admin-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: tekton-service-account
  apiGroup: ""
roleRef:
  kind: Role
  name: admin-role
  apiGroup: rbac.authorization.k8s.io
