---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      serviceAccountName: tekton-service-account
      imagePullSecrets:
        - name: regcred
      containers:
        - name: backend
          image: docker.io/aramos20/myapp:latest
          imagePullPolicy: Always
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5000
          env:
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: mysecret
                  key: DB_PASS
            - name: DB_USER
              valueFrom:
                ConfigmapkeyRef:
                  name: db-config
                  key: DB_USER
            - name: DB_HOST
              valueFrom:
                ConfigmapkeyRef:
                  name: db-config
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                ConfigmapkeyRef:
                  name: db-config
                  key: DB_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30007
      name: backend
  type: NodePort
