---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  serviceName: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15-alpine
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: DB_PASS

            - name: POSTGRES_USER
              valueFrom:
                ConfigmapkeyRef:
                  name: db-config
                  key: DB_USER

            - name: POSTGRES_HOST
              valueFrom:
                ConfigmapkeyRef:
                  name: db-config
                  key: DB_HOST

            - name: POSTGRES_DB
              valueFrom:
                ConfigmapkeyRef:
                  name: db-config
                  key: DB_NAME
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432
  Type: ClusterIP
---
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
type: Opaque
data:
  DB_PASS: bXlwYXNz
